### Add a metric
POST http://localhost:3000/metric HTTP/1.1
content-type: application/json

      {
        "timestamp": "2023-09-12T07:45:23.000Z",
        "name": "response_time",
        "value": 10
      }

### Create an article
GET http://localhost:3000/metrics/?name=cpu_usage&from=2023-09-09T02:27:32.231Z&to=2023-09-12T07:50:51.003Z&intervalUnit=hour HTTP/1.1
